# MySQL
#   brew install mysql
#
#   Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql'
#   
#   bundle install
#   mysql_secure_installation
#   brew tap homebrew/services
#   brew services start mysql
#   rake db:create && rake db:schema:load && rake db:setup
#   
#
default:
  

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  socket: /tmp/mysql.sock
  username: root
  password: Lannister85
  database: loggr_development
  
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  socket: /tmp/mysql.sock
  username: root
  password: Lannister85
  database: loggr_test

staging:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  socket: /tmp/mysql.sock
  username: root
  password: Lannister85
  database: loggr_staging

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  socket: /tmp/mysql.sock
  username: root
  password: Lannister85 # Don't forget to remove this here
  database: loggr_production

