# MySQL
#   brew install mysql
#
#   Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql'
#   
#   bundle install
#   mysql_secure_installation
#   brew tap homebrew/services
#   brew services start mysql
#   rake db:create && rake db:schema:load && rake db:setup
#   
#
default:
   

development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  timeout: 5000
  pool: 5
  username: dexterg
  password: alpha2
  database: loggr_development
  
test:
  adapter: postgresql
  encoding: utf8
  timeout: 5000
  pool: 5
  username: dexterg
  password: alpha2
  database: loggr_test

production:
  adapter: postgresql
  encoding: utf8
  timeout: 5000
  pool: 5
  database: loggr

